name: your_weather
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter  
  flutter_bloc: ^8.1.2
  flutter_launcher_icons: ^0.13.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/icon2.png"

flutter:


  uses-material-design: true


  assets:
    - images/

